### ISSUE TITLE
Error in API get Call

### ISSUE THREAD

**Issue by gabs77** [ebizmarts/mailchimp-lib#1]
https://github.com/ebizmarts/mailchimp-lib/blob/master/src/Mailchimp/ListsMembers.php#L115
It miss a 's' in 'list' (list/:listId/members/:email_md5) :  

return $this->master->call('list/'.$listId.'/members/'.$subscriberHash,$_params,Mailchimp::GET);

**Comment by gonzaloebiz** [comment]
Hi @gabs77 

thanks for pointing that!!!
