### ISSUE TITLE
After Installing mailchimp-lib Screen(Front/Back End) becomes blank

### ISSUE THREAD

**Issue by vrajeshpatel4u** [ebizmarts/mailchimp-lib#19]
Hello, I have installed Ebizmarts Mailchimp in Magento 2.2.5 new latest version in locally. All instruction I have followed even I have installed lib using composer and installed successfully. All magento commands I have run as per instructions. After last commands 'cache clean', when i access magento in locally, the screen becomes blank. Front end as well as back end becomes blank. I have attached all screenshot related this. In earlier version of Magento this extension works fine.  
![mailchimp lib](https://user-images.githubusercontent.com/40518060/44542841-92047c80-a72b-11e8-9838-9a7e70f96c05.png)
![mailchimp error](https://user-images.githubusercontent.com/40518060/44542842-92047c80-a72b-11e8-8413-4017542dd9c7.png)
![mailchimp error log](https://user-images.githubusercontent.com/40518060/44542844-929d1300-a72b-11e8-8317-dd0bc77d486b.png)

**Comment by gonzaloebiz** [comment]
Hi @vrajeshpatel4u 

thanks for choosing our extensions.
Take a look at the apache/nginx error log, typically these errors are there

Best
