### ISSUE TITLE
vendor/mailchimp/mc-magento2/Helper/Data.php::getSubscriberInterest $interestGroup->getGroupdata() NULL

### ISSUE THREAD

**Issue by thisisme** [ebizmarts/mailchimp-lib#24]
If $interestGroup->getGroupdata() is NULL in vendor/mailchimp/mc-magento2/Helper/Data.php::getSubscriberInterest we get 'Unable to unserialize value.' on all customers in Customers->All customers. Magento 2.2.6

**Comment by gonzaloebiz** [comment]
This is not an issue in the lib
