### ISSUE TITLE
Exceptions.php file does not exist

### ISSUE THREAD

**Issue by shinesoftware** [ebizmarts/mailchimp-lib#35]
Hello guys,

seems that the "version": "3.0.32" doesn't include the Exceptions.php file in /ebizmarts/mailchimp-lib/src/Mailchimp directory.

> Uncaught Exception: Warning: require_once(Mailchimp/Exceptions.php): failed to open stream: No such file or directory in /var/www/html/icepromotion/vendor/ebizmarts/mailchimp-lib/src/Mailchimp.php on line 20 in /var/www/html/icepromotion/vendor/magento/framework/App/ErrorHandler.php:61

Is there any update to do?

thanks

**Comment by gonzaloebiz** [comment]
Hi @shinesoftware 

thanks for your feedback. Take a look a the new relesase
