### ISSUE TITLE
Warning: Ambiguous class resolution

### ISSUE THREAD

**Issue by Stevie-Ray** [ebizmarts/mailchimp-lib#37]
When running `composer install --verbose --no-progress --no-interaction --op  
  timize-autoloader --no-dev --ignore-platform-reqs` we get the following warning:

Warning: Ambiguous class resolution, "Mailchimp_HttpError" was found in both "/builds/m2-clients/xxxxxxxx/vendor/ebizmarts/mailchimp-lib/src/Mailchimp/HttpError.php" and "/builds/m2-clients/xxxxxxxx/vendor/ebizmarts/mailchimp-lib/src/Mailchimp/Error.php", the first will be used.

Deploying Magento 2.4.x  with PHP 7.3.x

**Comment by gonzaloebiz** [comment]
Hi @Stevie-Ray 

chat version of mailchimp-lib are you using?

**Comment by Stevie-Ray** [comment]
3.0.33 thanks for the fix!

**Comment by gonzaloebiz** [comment]
you are welcome
