### ISSUE TITLE
\Mailchimp\Campaigns::get() does not return any response

### ISSUE THREAD

**Issue by jaycroll** [ebizmarts/mailchimp-lib#7]
Hi, I noticed that the method `\Mailchimp\Campaigns::get()` does not return any response.
https://github.com/ebizmarts/mailchimp-lib/blob/a9ff4c9820a0c42f4e4eae6a6adf3d67fa947bcb/src/Mailchimp/Campaigns.php#L104-L110

**Comment by gonzaloebiz** [comment]
hi @jaycroll 

thanks for your feedback.
